/**
 * The following code is automatically generated by the program .
 * Do not modify it manually !
 */
package com.allen.dayup.arithmetic;

import java.util.Objects;

public class AppSimplegatewayTriggerdeviceVo {
    /**
     * 自增长主键
     */
    private long id;
    /**
     * 用户id
     */
    private String userid;
    /**
     * 所属的简易网关id
     */
    private String iotid;
    /**
     * app_simplegateway所属id
     */
    private long mainid;
    /**
     * 触发iotid
     */
    private String triggeriotid;
    /**
     * 触发名称
     */
    private String triggername;
    /**
     * 触发描述
     */
    private String triggerremark;
    /**
     * 触发的属性名
     */
    private String propertyname;
    /**
     * 触发的属性值
     */
    private String propertyvalue;
    /**
     * 触发事件
     */
    private String event;

    private String roomname;

    private Boolean islinked;

    private long templateid;


    /**
     * 创建时间
     */
    private java.time.LocalDateTime createtime;
    /**
     * 更新时间
     */
    private java.time.LocalDateTime updatetime;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AppSimplegatewayTriggerdeviceVo that = (AppSimplegatewayTriggerdeviceVo) o;
        return mainid == that.mainid &&
                userid.equals(that.userid) &&
                iotid.equals(that.iotid) &&
                triggeriotid.equals(that.triggeriotid) &&
                triggername.equals(that.triggername);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userid, iotid, mainid, triggeriotid, triggername);
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getIotid() {
        return this.iotid;
    }

    public void setIotid(String iotid) {
        this.iotid = iotid;
    }

    public long getMainid() {
        return this.mainid;
    }

    public void setMainid(long mainid) {
        this.mainid = mainid;
    }

    public String getTriggeriotid() {
        return this.triggeriotid;
    }

    public void setTriggeriotid(String triggeriotid) {
        this.triggeriotid = triggeriotid;
    }

    public String getTriggername() {
        return this.triggername;
    }

    public void setTriggername(String triggername) {
        this.triggername = triggername;
    }

    public String getTriggerremark() {
        return this.triggerremark;
    }

    public void setTriggerremark(String triggerremark) {
        this.triggerremark = triggerremark;
    }

    public String getPropertyname() {
        return this.propertyname;
    }

    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname;
    }

    public String getPropertyvalue() {
        return this.propertyvalue;
    }

    public void setPropertyvalue(String propertyvalue) {
        this.propertyvalue = propertyvalue;
    }

    public String getEvent() {
        return this.event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getRoomname() {
        return roomname;
    }

    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }

    public Boolean getIslinked() {
        return islinked;
    }

    public void setIslinked(Boolean islinked) {
        this.islinked = islinked;
    }

    public java.time.LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(java.time.LocalDateTime createtime) {
        this.createtime = createtime;
    }

    public java.time.LocalDateTime getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(java.time.LocalDateTime updatetime) {
        this.updatetime = updatetime;
    }

    public long getTemplateid() {
        return templateid;
    }

    public void setTemplateid(long templateid) {
        this.templateid = templateid;
    }

    @Override
    public String toString() {
        return "AppSimplegatewayTriggerdeviceVo{" +
                "id=" + id +
                ", userid='" + userid + '\'' +
                ", iotid='" + iotid + '\'' +
                ", mainid=" + mainid +
                ", triggeriotid='" + triggeriotid + '\'' +
                ", triggername='" + triggername + '\'' +
                ", triggerremark='" + triggerremark + '\'' +
                ", propertyname='" + propertyname + '\'' +
                ", propertyvalue='" + propertyvalue + '\'' +
                ", event='" + event + '\'' +
                '}';
    }
}
